version: '3.1'
services:
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        ports:
          - "27017:27017"
          
    head-server:
        build: ./Head.Api
        restart: always
        ports:
            - 5000:80
            - 5001:443
        depends_on:
            - mongo
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        links:
          - mongo