name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build & publish the Docker image
      uses: docker/build-push-action@v1
      with:
        add_git_labels: true
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
        path: Miso.Api
        repository: cloud.enricleon.com/enricleon/miso-backend
        tags: latest
